[zstd]
name = "zstd"
desc = "Zstandard"
more = "Fast real-time compression algorithm"

[zsh]
name = "zsh"
desc = "Z shell"
more = "Paul Falstad wrote the first version of Zsh in 1990 while a student at Princeton University. The name zsh derives from the name of Yale professor Zhong Shao (then a teaching assistant at Princeton University) – Paul Falstad regarded Shao's login-id, 'zsh', as a good name for a shell"

[zle.Zsh]
name = "ZLE"
desc = "Zsh Line Editor"

[zopfli]
name = "Zopfli"
desc = "named after zöpfli, the Swiss German word for a snack-sized braided buttery bread"
more = "A data compression library that performs Deflate, gzip and zlib data encoding. It achieves higher compression ratios than mainstream Deflate and zlib implementations at the cost of being slower. Google first released Zopfli in February 2013 under the terms of Apache License 2.0"
see = 'Brotli'
